#!/usr/bin/env php
<?php

$argv = $_SERVER['argv'];

$stderr = fopen('php://stderr', 'w');

require dirname(__FILE__) . '/Packager/packager.php';

$executable = array_shift($argv);

$pkg = new Packager(array(
	dirname(__FILE__) . "/Packages/mootools-core", 
	dirname(__FILE__) . "/Packages/mootools-more",
	dirname(__FILE__) . "/Packages/mootools-extras", 	 
	dirname(__FILE__)
));

fwrite($stderr, "Packager is building Core, More, Extras, Site\n\n");
fwrite($stderr, "Included Components:\n");

$no_compat = false;

foreach ($argv as $arg){
	if ($arg == '-1.2compat'){
		array_erase($argv, $arg);
		$no_compat = true;
		break;
	}
}

$files = (empty($argv)) ? $pkg->get_all_files() : $pkg->components_to_files($argv);

$files = $pkg->complete_files($files);

foreach ($files as $file){
	fwrite($stderr, "- $file: [" . implode(", ", $pkg->get_file_provides($file)) . "]\n");
}

$output = $pkg->build($files, array(), array(), ($no_compat) ? array("1.2compat") : array());

echo $output;

fclose($stderr);

?>