#!/usr/bin/env php
<?php
$root = dirname(__FILE__);
$config_file = "$root/.config";
$configs = parse_ini_file($config_file);
echo "$root/build Site/Init -1.2compat > {$configs['export']} \n";
exec("$root/build Site/Init -1.2compat > {$configs['export']}");
exec("yui-compressor {$configs['export']} -o {$configs['export']}");
?>